[project]
name = "v4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "grpcio>=1.74.0",
    "grpcio-status>=1.74.0",
    "pandas>=2.3.2",
    "protobuf>=6.32.0",
    "pyarrow>=21.0.0",
    "pyspark==3.5.5",
]
